# EE-690 - Machine Learning
## Introduction to Numpy
# https://docs.python.org

## Contents
1. Creating 1-D Arrays
2. Creating 2-D Arrays
3. Creating n-D Arrays
4. Special Arrays
5. Operations on Arrays
6. Dot Product of Arrays
7. Initializing Arrays with Random Numbers
8. Built-in functions for Arrays
9. Indexing, Slicing, and Iterating with Arrays
10. Stacking together different Arrays
11. Splitting one array into several
12. Indexing with Boolean Arrays
13. Linear Algebra

In [2]:
import numpy as np

## 1. Creating 1-D Arrays

In [74]:
ar = np.array([12, -5, 2+4])
ar

array([12, -5,  6])

In [75]:
ar = np.array(['a', 'b', 'c'])
ar

array(['a', 'b', 'c'], dtype='<U1')

In [76]:
ar = np.array(['hello', "world", '!', 25])
ar

array(['hello', 'world', '!', '25'], dtype='<U5')

In [115]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [116]:
a.shape

(6,)

In [117]:
a.ndim

1

In [118]:
print(a.dtype)
print(a.dtype.name)
print(type(a))

int32
int32
<class 'numpy.ndarray'>


In [125]:
t1 = np.array([1, 2.5, 3], dtype=np.float)
print('t1: ', t1, t1.dtype)

t2 = t1.astype(int)
print('t2: ', t2, t2.dtype)

t1:  [1.  2.5 3. ] float64
t2:  [1 2 3] int32


## 2. Creating 2-D Arrays

In [81]:
z = np.array([[1, 2, 3], [4, 5, 6]])
z

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
a=np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(3, 2)
print(b, b.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [83]:
c = a.reshape(1,6)
print(a, a.shape)
print(c, c.shape,)

[1 2 3 4 5 6] (6,)
[[1 2 3 4 5 6]] (1, 6)


In [84]:
x = b.reshape(2, 3)
print(x, x.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [126]:
a = np.arange(12)
print(a, a.shape, a.ndim)
a = a.reshape(2,6)
print(a, a.shape, a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,) 1
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] (2, 6) 2


In [128]:
a = a.astype(np.float)
a

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]])

## 3. Creating n-D Arrays

In [3]:
s = np.array([[[ 1, 2, 3, 4],
        [ 5, 6, 7, 8],
        [ 9, 10, 11, 12]],
       [[ -1, -2, -3, -4],
        [ -5, -6, -7, -8],
        [ -9, -10, -11, -12]]])
print(s.shape)
print(s)

(2, 3, 4)
[[[  1   2   3   4]
  [  5   6   7   8]
  [  9  10  11  12]]

 [[ -1  -2  -3  -4]
  [ -5  -6  -7  -8]
  [ -9 -10 -11 -12]]]


## 4. Special Arrays

In [101]:
z1 = np.zeros(8)
print(z1)
z2 = np.zeros((3,5))
z2

[0. 0. 0. 0. 0. 0. 0. 0.]


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [111]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [112]:
np.ones((2,4,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [113]:
np.empty( (2,3) )

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [114]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [129]:
np.arange(2,5, 0.4)

array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8])

In [130]:
np.linspace(10, 100, 6)

array([ 10.,  28.,  46.,  64.,  82., 100.])

In [131]:
np.linspace(4, 8, 20)

array([4.        , 4.21052632, 4.42105263, 4.63157895, 4.84210526,
       5.05263158, 5.26315789, 5.47368421, 5.68421053, 5.89473684,
       6.10526316, 6.31578947, 6.52631579, 6.73684211, 6.94736842,
       7.15789474, 7.36842105, 7.57894737, 7.78947368, 8.        ])

## 5. Operations on Arrays

In [142]:
a = np.array([[1, 2, 3]])
b = np.array([[2, 4, 6]])
print(a + b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)
print(np.sin(a))
print(10 * np.sin(a) +100)

[[3 6 9]]
[[-1 -2 -3]]
[[ 2  8 18]]
[[0.5 0.5 0.5]]
[[1 4 9]]
[[0.84147098 0.90929743 0.14112001]]
[[108.41470985 109.09297427 101.41120008]]


In [161]:
a = np.array([[1, 2, 3]])
a += 1
a

array([[2, 3, 4]])

## 6. Dot Product of Arrays

In [153]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[-2,3],[-4,-5],[-6,-7]])
c = np.array([[10, 20, 30], [100, 200, 300]])
print(a.shape, b.shape, c.shape)
print(a)
print(b)
print(c)

(3, 2) (3, 2) (2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[-2  3]
 [-4 -5]
 [-6 -7]]
[[ 10  20  30]
 [100 200 300]]


In [154]:
a * b

array([[ -2,   6],
       [-12, -20],
       [-30, -42]])

In [158]:
a.dot(c)

array([[ 210,  420,  630],
       [ 430,  860, 1290],
       [ 650, 1300, 1950]])

In [159]:
c.dot(a)

array([[ 220,  280],
       [2200, 2800]])

## 7. Initializing Arrays with Random Numbers

In [163]:
a = np.random.random(5)
a

array([0.23144577, 0.65407517, 0.747624  , 0.1408866 , 0.01426013])

In [165]:
b = np.random.random((2,3))
b

array([[0.51775243, 0.51190261, 0.21312608],
       [0.68163964, 0.90334165, 0.52857851]])

In [166]:
c = np.ones((2,3))
b + c

array([[1.51775243, 1.51190261, 1.21312608],
       [1.68163964, 1.90334165, 1.52857851]])

## 8. Built-in functions for Arrays

In [168]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [170]:
a.max()

4

In [171]:
a.min()

1

In [173]:
a.max(axis=0)

array([3, 4])

In [174]:
a.max(axis=1)

array([2, 4])

In [175]:
a.sum()

10

In [176]:
a.sum(axis=0)

array([4, 6])

In [177]:
a.sum(axis=1)

array([3, 7])

## 9. Indexing, Slicing, and Iterating with Arrays

In [179]:
a = np.arange(10)**2
print(a)
print(a[2])
a[2:5]

[ 0  1  4  9 16 25 36 49 64 81]
4


array([ 4,  9, 16], dtype=int32)

In [5]:
a = np.array([ 1, 2, 3, 4, 5, 6, 7])
a[:6:2] = -555
a

array([-555,    2, -555,    4, -555,    6,    7])

In [6]:
a[ : :-1]

array([   7,    6, -555,    4, -555,    2, -555])

In [187]:
for i in a:
    print(i**2)

308025
4
308025
16
308025
36
49


In [189]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4))
b

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.],
       [30., 31., 32., 33.],
       [40., 41., 42., 43.]])

In [192]:
print(b[2,3], '\n')

print(b[0:5, 1])

print(b[ : ,1])

print(b[1:3, : ]) 

23.0 

[ 1. 11. 21. 31. 41.]
[ 1. 11. 21. 31. 41.]
[[10. 11. 12. 13.]
 [20. 21. 22. 23.]]


In [193]:
b[-1]

array([40., 41., 42., 43.])

In [195]:
for row in b:
    print(row)

[0. 1. 2. 3.]
[10. 11. 12. 13.]
[20. 21. 22. 23.]
[30. 31. 32. 33.]
[40. 41. 42. 43.]


In [197]:
for element in b.flat[5:15]:
    print(element)

11.0
12.0
13.0
20.0
21.0
22.0
23.0
30.0
31.0
32.0


In [203]:
x = np.array([[1,2], [3,4]])
for k in x.flat: 
    print(k)
    
for m in x.ravel():
    print(m)

1
2
3
4
1
2
3
4


In [208]:
x = np.array([[1,2], [3,4], [5,6]])
print(x, x.shape)
print(x.T, x.T.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2)
[[1 3 5]
 [2 4 6]] (2, 3)


In [211]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)
print(a.reshape((1,6)))
print(a)

a.resize((1,6))
print(a)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]


## 10. Stacking together different Arrays

In [212]:
a = np.floor(10*np.random.random((2,3)))
print(a)

b = np.floor(10*np.random.random((2,3)))
print(b)

[[6. 2. 9.]
 [1. 8. 2.]]
[[9. 4. 0.]
 [5. 9. 3.]]


In [213]:
x = np.vstack((a,b))
print(x)

y = np.hstack((a,b))
print(y)

[[6. 2. 9.]
 [1. 8. 2.]
 [9. 4. 0.]
 [5. 9. 3.]]
[[6. 2. 9. 9. 4. 0.]
 [1. 8. 2. 5. 9. 3.]]


In [214]:
# "column_stack" stacks 1D arrays as columns into a 2D array.
# similar to "hstack" which is used for 2D arrays only

np.column_stack((a,b))

array([[6., 2., 9., 9., 4., 0.],
       [1., 8., 2., 5., 9., 3.]])

In [215]:
a = np.array([4.,2.])
b = np.array([3.,8.])
np.column_stack((a,b))

array([[4., 3.],
       [2., 8.]])

In [216]:
np.hstack((a,b)) 

array([4., 2., 3., 8.])

In [218]:
# this allows to have a 2D columns vector
from numpy import newaxis
a[:,newaxis]

array([[4.],
       [2.]])

In [220]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [221]:
np.hstack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

## 11. Splitting one array into several

In [223]:
a = np.floor(10*np.random.random((2,12)))
a

array([[0., 1., 5., 1., 3., 7., 0., 3., 6., 2., 6., 0.],
       [0., 0., 6., 5., 9., 2., 7., 6., 9., 3., 2., 7.]])

In [224]:
np.hsplit(a,3)   # Split a into 3

[array([[0., 1., 5., 1.],
        [0., 0., 6., 5.]]), array([[3., 7., 0., 3.],
        [9., 2., 7., 6.]]), array([[6., 2., 6., 0.],
        [9., 3., 2., 7.]])]

In [225]:
np.hsplit(a,(3,4))   # Split a after the third and the fourth column

[array([[0., 1., 5.],
        [0., 0., 6.]]), array([[1.],
        [5.]]), array([[3., 7., 0., 3., 6., 2., 6., 0.],
        [9., 2., 7., 6., 9., 3., 2., 7.]])]

In [226]:
# Simple Array Copy
a = np.arange(12)
b = a            # no new object is created
print(b is a)    # a and b are two names for the same ndarray object

b.shape = 3,4    # changes the shape of a
print(a.shape)

True
(3, 4)


In [227]:
# Deep Copy
d = a.copy()    # a new array object with new data is created
d is a

False

In [228]:
d[0,0] = 9999
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [232]:
a = np.arange(12)**2
print(a)

i = np.array([2,1,8,5,5])     # an array of indices
print(a[i])                   # the elements of a at the positions i

j = np.array([[3,4],[2,8]])   # a bidimensional array of indices
a[j]         

[  0   1   4   9  16  25  36  49  64  81 100 121]
[ 4  1 64 25 25]


array([[ 9, 16],
       [ 4, 64]], dtype=int32)

In [243]:
# When the indexed array a is multidimensional, a single array of indices
# refers to the first dimension of a. 
# The following example shows this behavior by converting
# an image of labels into a color image using a palette.

palette = np.array([[0,0,0],         # black
                    [255,0,0],       # red
                    [0,255,0],       # green
                    [0,0,255],       # blue
                    [255,255,255]])  # white

image = np.array([[ 0, 1, 2, 0 ],    # values correspond to color in palette
                  [ 0, 3, 4, 0 ]])
palette[image]                       # the (2,4,3) color image

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [244]:
a[b] = 0 
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

## 12. Indexing with Boolean Arrays

In [242]:
a = np.arange(12).reshape(3,4)
b = a > 4
print(b)

print(a[b])

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]


## 13. Linear Algebra

In [259]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print('a=', a)

print('transpose(a)=', a.transpose(), '\n')

print('inverse of a = ', np.linalg.inv(a), '\n')

u = np.eye(2)
print('u = np.eye(2)=', u, '\n')

j = np.array([[0.0, -1.0], [1.0, 0.0]])
print('j=', j)
print('np.dot(j,j)=', np.dot (j, j), '\n')

print('np.trace(u)', np.trace(u), '\n')

y = np.array([[5.], [7.]])
print('a=', a, 'y=', y)
print('np.linalg.solve(a, y) =', np.linalg.solve(a, y), '\n')

print('Eigenvalue =', np.linalg.eig(j))

a= [[1. 2.]
 [3. 4.]]
transpose(a)= [[1. 3.]
 [2. 4.]] 

inverse of a =  [[-2.   1. ]
 [ 1.5 -0.5]] 

u = np.eye(2)= [[1. 0.]
 [0. 1.]] 

j= [[ 0. -1.]
 [ 1.  0.]]
np.dot(j,j)= [[-1.  0.]
 [ 0. -1.]] 

np.trace(u) 2.0 

a= [[1. 2.]
 [3. 4.]] y= [[5.]
 [7.]]
np.linalg.solve(a, y) = [[-3.]
 [ 4.]] 

Eigenvalue = (array([0.+1.j, 0.-1.j]), array([[0.70710678+0.j        , 0.70710678-0.j        ],
       [0.        -0.70710678j, 0.        +0.70710678j]]))


## Stacking Vectors

In [ ]:
x = np.arange(0,10,2)                     # x=([0,2,4,6,8])
y = np.arange(5)                          # y=([0,1,2,3,4])
m = np.vstack([x,y])                      # m=([[0,2,4,6,8],
                                          #     [0,1,2,3,4]])
xy = np.hstack([x,y])                     # xy =([0,2,4,6,8,0,1,2,3,4])